language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel pytest
  - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
  - pip install cvxopt
  - pip install pytest pytest-cov coveralls
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - python setup.py test
after_success:
  - coveralls
