language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
install:
  - pip install --upgrade pip setuptools wheel pytest
  - pip install --only-binary=numpy numpy
  - pip install --only-binary=scipy scipy
  - pip install --only-binary=matplotlib matplotlib
  - python setup.py install
script:
  - python setup.py test